<div id="header">
	<div id="logo">
		Task Console
	</div>		
	<div id="lnks">
		<?php if( isset( $this->user ) ){ ?>
			<?php if( $this->user != false ){ ?>
				Welcome, <?= $this->user->getFirstName() ?> | <a href="<?= $this->baseUrl(); ?>/index/settings"><img src="<?= $this->baseUrl() ?>/html/images/cog.png" style="vertical-align: middle;"></img> settings</a> | <a href="<?= $this->baseUrl(); ?>/user/logout"><img src="<?= $this->baseUrl() ?>/html/images/house_go.png" style="vertical-align: middle;"></img> logout</a>
			<?php } ?>
		<?php } ?>		
	</div>			
</div>
