<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Task Console</title>
			
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/html/scripts/ext-3.4.0/resources/css/ext-all.css"></link>
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/html/scripts/ext-3.4.0/resources/css/xtheme-gray.css"></link>	
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/html/styles/main.css" />
    <link rel="icon" type="image/png" href="<?= $this->baseUrl(); ?>/html/images/ohapps_icon.png" />
	
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/ext-3.4.0/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/ext-3.4.0/ext-all.js"></script>    
    <script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/ext-3.4.0/examples/ux/MultiSelect.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/ext_extensions/Ext.ux.EasyEditorGridPanel.js"></script>        						
    <script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/main.js"></script>
    
    <script type="text/javascript">

    	Ext.BLANK_IMAGE_URL = '<?= $this->baseUrl(); ?>/html/scripts/ext-3.4.0/resources/images/default/s.gif' ;  	  	
	 	Ext.QuickTips.init();    
	 	Ext.data.Connection.prototype.disableCaching = false;
	  	Ext.MessageBox.minWidth = 400;	  	
	
	  	var ynss = new Ext.data.SimpleStore( { id: 0, fields: ["key", "val"], data : [ ["1","yes"], ["0","no"] ] } ) ;	  	
	
    </script>                    
	
</head>
