<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>TaskConsole</title>
			
    <link rel="stylesheet" type="text/css" href="/scripts/ext-3.0.0/resources/css/ext-all.css"></link>
    <link rel="stylesheet" type="text/css" href="/scripts/ext-3.0.0/resources/css/xtheme-gray.css"></link>
	<link rel="stylesheet" type="text/css" href="/scripts/ext_extensions/gridFilter/resources/style.css" />
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/html/styles/main.css" />
    <link rel="icon" type="image/png" href="/home/html/images/ohapps_icon.png" />
	
	<script type="text/javascript" src="/scripts/ext-3.0.0/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="/scripts/ext-3.0.0/ext-all.js"></script>    
    <script type="text/javascript" src="/scripts/ext_extensions/Ext.ux.EasyEditorGridPanel.js"></script>        	
	<script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/menu/EditableItem.js"></script>
    <script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/menu/RangeMenu.js"></script>
    <script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/grid/GridFilters.js"></script>
    <script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/grid/filter/Filter.js"></script>
    <script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/grid/filter/StringFilter.js"></script>
    <script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/grid/filter/DateFilter.js"></script>
    <script type="text/javascript" src="/scripts/ext_extensions/gridFilter/ux/grid/filter/ListFilter.js"></script>				
    <script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/main.js"></script>            
	
</head>
