<script type="text/javascript">
		
   				
/*********************
* TASK FILTER OBJECT
********************/
var task_filter = new Object();
task_filter.category = '';
task_filter.project = '';
task_filter.priorities = '';

function filterTasks(filterBy,filterVal){

	switch(filterBy){
		case "category":
			if( filterVal != '' ){
				node = task_filter_tree.getNodeById('category_' + filterVal);
				node.getUI().addClass('filterApply');				
			}
			if( task_filter.category != filterVal && task_filter.category != '' ){
				node = task_filter_tree.getNodeById('category_' + task_filter.category);
				node.getUI().removeClass('filterApply');
			}
			task_filter.category = filterVal;
			break;			
		case "project":
			task_filter.project = filterVal;
			break;
	}

	var priorities = ''; 
	selNodes = task_filter_tree.getChecked();
    Ext.each(selNodes, function(node){
        if(priorities.length > 0){
            priorities += ',';
        }
        priorities += node.id;
    });
	task_filter.priorities = priorities;
    
	task_queue_store.load({ params: { start: 0, limit: 50 } });
   	task_pending_store.load({ params: { start: 0, limit: 50 } });
   	task_complete_store.load({ params: { start: 0, limit: 50 } });
   	task_upcoming_store.load({ params: { start: 0, limit: 50 } });
	
}


/*********************
* TASK FILTER TREE
********************/
var task_filter_tree = new Ext.tree.TreePanel({
        
        title: "Filter Tasks",
        autoScroll:true,
        animate:true,        
        containerScroll: true,                                                 
        region: "west",
        split:true,
        width: 200,
        minSize: 200,
        maxSize: 300,
        layout:'fit',
        margins:'5 0 5 5',
        collapsible: true,
        
        loader: new Ext.tree.TreeLoader({
            dataUrl: '<?= $this->baseUrl(); ?>/projects/loadtree',
            preloadChildren: false            
        }),
        
        root: new Ext.tree.AsyncTreeNode({
            text: 'All Tasks',
            id: 'root',
            cls: 'folder',
            href: "javascript:loadTasks( '', '' )",
            expanded: false
        }),
        
        rootVisible: true,

        listeners: {
		    'checkchange': function(node, checked){
				filterTasks('','');
		    }			
		}

        
});

	
/*********************
* TASK TAB
********************/
var Task = Ext.data.Record.create([
	{name: "ID", type: "string"},
	{name: "PROJECT", type: "string"},
	{name: "DESCRIPTION", type: "string"},
	{name: "PRIORITY", type: "string"},
	{name: "DUE_DATE", type: "date", dateFormat: "Y-m-d"},    
	{name: "COMPLETED", type: "date", dateFormat: "Y-m-d"},
	{name: "DISPLAY_DATE", type: "date", dateFormat: "Y-m-d"},
	{name: "COMPLETE", type: "string"},
	{name: "QUEUE_ORDER", type: "float"}
]);

var task_queue_sm = new Ext.grid.CheckboxSelectionModel();

var task_queue_cm = new Ext.grid.ColumnModel([	 	
	task_queue_sm,
	{ id: "id", header: "ID", dataIndex: "ID", hidden: true },	
	{ header: "Priority", dataIndex: "PRIORITY", width: 60, sortable: true },
	{ header: "Due Date", dataIndex: "DUE_DATE", width: 100, renderer: Ext.util.Format.dateRenderer("d-M-Y"), sortable: true },
	{ header: "Project", dataIndex: "PROJECT", width: 250, sortable: true },
	{ id: "queue_description", header: "Description", dataIndex: "DESCRIPTION", width: 200, sortable: true }       
	
]);
                           	
var task_queue_store = new Ext.data.Store({ 
	url: "<?= $this->baseUrl(); ?>/projects/usertasks/status/queue",
	baseParams: task_filter, 
	remoteSort: true,
	reader: new Ext.data.JsonReader({ totalProperty: "results", root: "data", id: "ID" }, Task), 
	autoLoad: false 
});		

var task_queue_pagingbar = new Ext.PagingToolbar({
    pageSize: 50,
    store: task_queue_store,
    displayInfo: true,
    displayMsg: "Displaying tasks {0} - {1} of {2}",
    emptyMsg: "No tasks to display"
});

var task_queue_grid = new Ext.ux.EasyEditorGridPanel({
                           		
	title: 'Queue',		
	store: task_queue_store,
	cm: task_queue_cm,    	
	autoExpandColumn: "queue_description",	   
	stripeRows: true,
	selModel: task_queue_sm,
	loadMask: true,
	tbar: [
           	{
           	  	text: "Mark Completed",
           	  	icon: "<?= $this->baseUrl(); ?>/html/images/accept.png",
           	  	handler : function(){
             	  	/*
           	  		task_grid.postSelectedIDs({ 
           	  			url: "<?= $this->baseUrl(); ?>/projects/markcomplete", 
           	  			postParam : "data[]", 
           	  			maskSave: true,
           	  			reloadOnChange: true    						
           	  		});
         	  		*/
           	  	}
           },
		   '|',
		   {
           		text: "Delete",
               	icon: "<?= $this->baseUrl(); ?>/html/images/delete.png",
               	handler : function(){
                	
               	}
           }                                       
       	],
	bbar: task_queue_pagingbar 	    

});

var task_pending_sm = new Ext.grid.CheckboxSelectionModel();

var task_pending_cm = new Ext.grid.ColumnModel([
	task_pending_sm,
	{ id: "id", header: "ID", dataIndex: "ID", hidden: true },	
	{ header: "Priority", dataIndex: "PRIORITY", width: 60 },
	{ header: "Due Date", dataIndex: "DUE_DATE", width: 100, renderer: Ext.util.Format.dateRenderer("d-M-Y") },
	{ header: "Project", dataIndex: "PROJECT", width: 250 },
	{ id: "pending_description", header: "Description", dataIndex: "DESCRIPTION", width: 200 }                                                 
]);
                                                                     	
var task_pending_store = new Ext.data.Store({ 
	url: "<?= $this->baseUrl(); ?>/projects/usertasks/status/pending",
	baseParams: task_filter, 
	remoteSort: true,
	reader: new Ext.data.JsonReader({ totalProperty: "results", root: "data", id: "ID" }, Task), 
	autoLoad: false 
});		

var task_pending_pagingbar = new Ext.PagingToolbar({
	pageSize: 50,
	store: task_pending_store,
	displayInfo: true,
	displayMsg: "Displaying tasks {0} - {1} of {2}",
	emptyMsg: "No tasks to display"
});

var task_pending_grid = new Ext.ux.EasyEditorGridPanel({
                                                                     		
	title: 'Pending',		
	store: task_pending_store,
	cm: task_pending_cm,    	
	autoExpandColumn: "pending_description",	   
	stripeRows: true,
	selModel: task_pending_sm,
	loadMask: true,
	tbar: [
          	{
          	  	text: "Mark Completed",
          	  	icon: "<?= $this->baseUrl(); ?>/html/images/accept.png",
          	  	handler : function(){
            	  	/*
          	  		task_grid.postSelectedIDs({ 
          	  			url: "<?= $this->baseUrl(); ?>/projects/markcomplete", 
          	  			postParam : "data[]", 
          	  			maskSave: true,
          	  			reloadOnChange: true    						
          	  		});
        	  		*/
          	  	}
          	},
		   	'|',
		  	{
          		text: "Delete",
              	icon: "<?= $this->baseUrl(); ?>/html/images/delete.png",
              	handler : function(){
               	
              	}
          	},
          	'|',
		  	{
          		text: "Add To Queue",
              	icon: "<?= $this->baseUrl(); ?>/html/images/add.png",
              	handler : function(){
               	
              	}
          	}                                       
      	],
	bbar: task_pending_pagingbar 	    

});

var task_complete_sm = new Ext.grid.CheckboxSelectionModel();

var task_complete_cm = new Ext.grid.ColumnModel([
	task_complete_sm,
	{ id: "id", header: "ID", dataIndex: "ID", hidden: true },	
	{ header: "Priority", dataIndex: "PRIORITY", width: 60 },
	{ header: "Completed", dataIndex: "COMPLETED", width: 100, renderer: Ext.util.Format.dateRenderer("d-M-Y") },
	{ header: "Project", dataIndex: "PROJECT", width: 250 },
	{ id: "complete_description", header: "Description", dataIndex: "DESCRIPTION", width: 200 }                                                 
]);
                                                                                                                 	
var task_complete_store = new Ext.data.Store({ 
	url: "<?= $this->baseUrl(); ?>/projects/usertasks/status/complete",
	baseParams: task_filter, 
	remoteSort: true, 
	reader: new Ext.data.JsonReader({ totalProperty: "results", root: "data", id: "ID" }, Task), 
	autoLoad: false 
});		

var task_complete_pagingbar = new Ext.PagingToolbar({
	pageSize: 50,
	store: task_complete_store,
	displayInfo: true,
	displayMsg: "Displaying tasks {0} - {1} of {2}",
	emptyMsg: "No tasks to display"
});

var task_complete_grid = new Ext.ux.EasyEditorGridPanel({
                                                                                                                 		
	title: 'Complete',		
	store: task_complete_store,
	cm: task_complete_cm,    	
	autoExpandColumn: "complete_description",	   
	stripeRows: true,
	selModel: task_complete_sm,
	loadMask: true,
	tbar: [
         	{
         	  	text: "Mark Incompleted",
         	  	icon: "<?= $this->baseUrl(); ?>/html/images/accept.png",
         	  	handler : function(){
           	  	/*
         	  		task_grid.postSelectedIDs({ 
         	  			url: "<?= $this->baseUrl(); ?>/projects/markcomplete", 
         	  			postParam : "data[]", 
         	  			maskSave: true,
         	  			reloadOnChange: true    						
         	  		});
       	  		*/
         	  	}
         	},
		   	'|',
		  	{
         		text: "Delete",
             	icon: "<?= $this->baseUrl(); ?>/html/images/delete.png",
             	handler : function(){
              	
             	}
         	}                                       
     	],
	bbar: task_complete_pagingbar 	    

});

var task_upcoming_sm = new Ext.grid.CheckboxSelectionModel();

var task_upcoming_cm = new Ext.grid.ColumnModel([
	task_upcoming_sm,
	{ id: "id", header: "ID", dataIndex: "ID", hidden: true },	
	{ header: "Priority", dataIndex: "PRIORITY", width: 60 },
	{ header: "Display Date", dataIndex: "DISPLAY_DATE", width: 100, renderer: Ext.util.Format.dateRenderer("d-M-Y") },
	{ header: "Project", dataIndex: "PROJECT", width: 250 },
	{ id: "upcoming_description", header: "Description", dataIndex: "DESCRIPTION", width: 200 }                                                 
]);
                                                                                                                                                              	
var task_upcoming_store = new Ext.data.Store({ 
	url: "<?= $this->baseUrl(); ?>/projects/usertasks/status/upcoming",
	baseParams: task_filter, 
	remoteSort: true, 
	reader: new Ext.data.JsonReader({ totalProperty: "results", root: "data", id: "ID" }, Task), 
	autoLoad: false 
});		

var task_upcoming_pagingbar = new Ext.PagingToolbar({
	pageSize: 50,
	store: task_upcoming_store,
	displayInfo: true,
	displayMsg: "Displaying tasks {0} - {1} of {2}",
	emptyMsg: "No tasks to display"
});

var task_upcoming_grid = new Ext.ux.EasyEditorGridPanel({
                                                                                                                                                              		
	title: 'Upcoming',		
	store: task_upcoming_store,
	cm: task_upcoming_cm,    	
	autoExpandColumn: "upcoming_description",	   
	stripeRows: true,
	selModel: task_upcoming_sm,
	loadMask: true,
	tbar: [        	
		  	{
        		text: "Delete",
            	icon: "<?= $this->baseUrl(); ?>/html/images/delete.png",
            	handler : function(){
             	
            	}
        	}                                       
    	],
	bbar: task_upcoming_pagingbar 	    

});

var task_tabs = new Ext.TabPanel({
	
	activeTab:0,                                                	
	deferredRender: false,
	region: 'center',
	plain: true,
	margins:'5 5 5 0',
				                        
	items:	[                                                
				task_queue_grid,
				task_pending_grid,
				task_complete_grid,
				task_upcoming_grid                                                              	                        
			]	
		                                        
});


	
/*********************
* TAB PANEL
********************/
	 	
var tab_panel = new Ext.TabPanel({
	                    	
	activeTab:0,                                                	
	deferredRender: false,
	region: 'center',
	plain: true,
	margins:'5',
				                        
	items:	[                                                
	      		{
		      		title: "<span style='font-size: 14px;'>Projects</span>",		      		
	      		},{
		      		title: "<span style='font-size: 14px;'>Tasks</span>",
		      		layout: "border",
		      		items: [
						task_filter_tree,	
						task_tabs  		
				    ],
				    tbar: 	[
						   		{ 
						        	text: "New Task",		            
						            icon: "<?= $this->baseUrl() ?>/html/images/application_edit.png",
						            handler : function(){
						   				newTasks();
						            }
						      	},
						      	'-',
						      	{ 
						        	text: "New Project",		            
						            icon: "<?= $this->baseUrl() ?>/html/images/application_cascade.png",
						            handler : function(){
						   				
						            }
						      	},
						      	'-',
						      	{ 
						        	text: "Edit Categories",		            
						            icon: "<?= $this->baseUrl() ?>/html/images/cog.png",
						            handler : function(){
						   				
						            }
						      	}
							]
	      		},{
		      		title: "<span style='font-size: 14px;'>Notes</span>"
	      		}	                                                                            	                        
			]
		                                        
});





/**************************************
 * TASK DETAIL WINDOW
 *************************************/

var project_store = new Ext.data.Store({ 
	url: "<?= $this->baseUrl(); ?>/projects/userprojects", 
	reader: new Ext.data.JsonReader({ root: "data", id: "ID" }, ["ID","DESCRIPTION"] ), 
	autoLoad: true 
});

var project_combo = new Ext.form.ComboBox({ 
	fieldLabel: "Project", 
	hiddenName: "PROJ_ID", 
	width: 390,
	allowBlank: true, 
	store: project_store, 
	valueField: "ID", 
	displayField: "DESCRIPTION", 
	typeAhead: true, 
	mode: "local", 
	triggerAction: "all", 
	emptyText: " ", 
	selectOnFocus: true, 
	editable: false 
});

var priority_store = new Ext.data.Store({ 
	url: "<?= $this->baseUrl(); ?>/projects/priorities", 
	reader: new Ext.data.JsonReader({ root: "data", id: "ID" }, ["ID","DESCRIPTION"] ), 
	autoLoad: true 
});

var priority_combo = new Ext.form.ComboBox({ 
	fieldLabel: "Priority", 
	hiddenName: "PRIORITY_ID",
	value: "2",
	width: 100,
	allowBlank: false, 
	store: priority_store, 
	valueField: "ID", 
	displayField: "DESCRIPTION", 
	typeAhead: true, 
	mode: "local", 
	triggerAction: "all", 
	emptyText: " ", 
	selectOnFocus: true, 
	editable: false 
});

var complete_combo = new Ext.form.ComboBox({ 
	fieldLabel: "Complete", 
	hiddenName: "COMPLETE", 
	value: "no",
	width: 100,
	allowBlank: false, 
	store: ynss, 
	valueField: "key", 
	displayField: "val", 
	typeAhead: true, 
	mode: "local", 
	triggerAction: "all", 
	emptyText: " ", 
	selectOnFocus: true, 
	editable: false 
});

var recur_unit_type_store = new Ext.data.SimpleStore({ 
	fields: ["label", "val"], 
	data : [ 
	    		["days","days"], 
	    		["months","months"], 
	    		["years","years"]
	       ] 	     	
});

var map = new Ext.KeyMap(document, 
		[ 
			{
	 			key: Ext.EventObject.ENTER,
				ctrl:true,
		        shift:true,
				fn: newTasks,
				scope: this
			},{
				key: Ext.EventObject.INSERT,
				ctrl:true,
		        shift:true,
				fn: saveTasks,
				scope: this
			}
		]
);

var task_form = new Ext.form.FormPanel({
	
	id: "task_form",
	labelWidth: 80,
	baseCls: "x-plain",                      
    defaultType: "textfield",
	buttonAlign: "right",
	keys: map,	           	
        
    items: [												
		{ 
			xtype: "textarea",			
			hideLabel: true, 
			name: "DESCRIPTION", 
			width: 550,
			height: 100,
			allowBlank: false
		},
		project_combo,
		{ 
			xtype: "panel",  
			baseCls: "x-plain",                      
	      	layout:"column",
	      	items:[
		              {   
		                 columnWidth:.50, 
		                 layout: "form",             
						 baseCls: "x-plain",                                        
		                 items: [		                 				                 			
									priority_combo		
		                 		]
		              },{   
		                 columnWidth:.50, 
						 baseCls: "x-plain",                      
		                 layout: "form",		                                                
		                 items: [									
									{ 
										xtype: "datefield", 
										fieldLabel: "Due Date", 
										name: "DUE_DATE", 
										width: 100,
										allowBlank: true, 
										format: "Y-m-d" 
									}
									/*
									,
									{ 
										xtype: "checkbox",
										<?php if( $this->gdata_enabled == false ){ ?> 
											hidden: true,
											hideLabel: true, 
										<?php } ?> 
										fieldLabel: "Display on Google Calendar", 
										name: "DISP_ON_GCAL",
										inputValue: "1"																				 
									}
									*/
		                 		]
		              }
		      	  ]
	    },{
            xtype: 'fieldset',
            title: 'Recurrence',            
            autoHeight:true,
            labelWidth: 400,                        
            items :[	
						{ 
							xtype: "panel",  
							baseCls: "x-plain",                      
						  	layout:"column",
						  	items:[
						              {   
						                 columnWidth:.85, 
						                 layout: "form",             
										 baseCls: "x-plain",                                        
						                 items: [
						                 			
						                 			{
									                	xtype: 'numberfield',
									                	width: 50,	
								                    	fieldLabel: 'Generate a copy of this task at the specified time from completion',
								                    	name: 'RECUR_UNITS'
								                	}		
						                 		]
						              },{   
						                 columnWidth:.15, 
										 baseCls: "x-plain",                      
						                 layout: "form",                               
						                 items: [
													{
														xtype: 'combo',
														hideLabel: true, 
														hiddenName: "RECUR_UNIT_TYPE",
														value: "days", 			            	
														width: 75,
														allowBlank: true, 
														store: recur_unit_type_store, 
														valueField: "val", 
														displayField: "label", 
														typeAhead: true, 
														mode: "local", 
														triggerAction: "all", 
														emptyText: " ", 
														selectOnFocus: true, 
														editable: false	                    	
													}
						                 		]
						              }
						      	]
						}                                                                                                                                                                                                        	
            		]
        },{ 
			xtype: "hidden",
			name: "ID"
		}
    ],
	
	buttons: [  
       	{ 			
			text: "SAVE", 
			handler: function(){ 
				
				saveTasks();							
				
			} 
		},{ 
			text: "DELETE", 
			handler: function(){ 
				
				Ext.MessageBox.confirm("Confirm", "Are you sure you want to delete this item?", function(btn){ 
                	if ( btn == "yes"){
				 
						Ext.Ajax.request({
		   					url: '<?= $this->baseUrl(); ?>/projects/deletetasks',
							params: { data: task_form.getForm().findField("ID").getValue() },
		   					success: function(){
								reloadTasks();
								task_window.hide(); 
							},
		   					failure: function(){
								Ext.Msg.alert("Error", "The task could not be deleted.");
							}   					
						});
						
					}
                });  
			} 
		},{ 
			text: "CLOSE", 
			handler: function(){ 
				task_window.hide(); 
			} 
		}					
	]			
	    	
});


task_window = new Ext.Window({
                                        
    title: "Task Details",                                            	  
    bodyStyle:"padding:5px;",
    closeAction: 'hide',
	modal: true,
	width: 600,
	focus: function(){ this.items.item(0).items.item(0).focus(); },
    items: task_form
    
});


function newTasks(){
	task_window.show();
	task_form.getForm().reset();	
	project_combo.setValue( task_filter.project );
	task_window.center();
}


function saveTasks(){		
	
	if( task_window.isVisible() ){ 
	
		if ( task_form.getForm().isValid() ){
			
			task_form.getForm().submit({
	        	url: "<?= $this->baseUrl(); ?>/projects/savetask", 
	            waitMsg:"Saving Task ...",                                   
	            success: function(){
	        		filterTasks('','');
					task_window.hide(); 
	            },
	            failure: function(){ 
	              	Ext.Msg.alert("Error", "The task could not be saved."); 
	            }
	        });
			 
		}
	
	}	
	
}


Ext.onReady(function() {


	/*********************
	* LAYOUT
	********************/
   	var viewport = new Ext.Viewport({
        
        layout:'border',
        style:'background: #DFDFDF;',
        items:	[ 
             		new Ext.BoxComponent({ 
                     	region:'north',
                     	el: 'header',
                     	height: 40
                 	}),             		 
             		tab_panel,             		
             		new Ext.BoxComponent({ 
                     	region:'south',
                     	el: 'footer',
                     	height: 40
                 	})
             	]
             
   	});

   	task_filter_tree.getRootNode().expand(
   		true,
   		false,
   		function(){ 
   	   		filterTasks('',''); 
   		}   		
   	);   			
   	   	   	
});
	
</script>