<script type="text/javascript">


var App = new Ext.Application({
	
	name : 'TaskConsole',	
	useLoadMask : true,	
	launch : function () {	

		TaskConsole.views.notesListToolbar = new Ext.Toolbar({
			id: 'notesListToolbar',
			title: 'My Notes'
		});
		 
		TaskConsole.views.notesListContainer = new Ext.Panel({
			id: 'notesListContainer',
			layout: 'fit',
			html: 'This is the notes list container',
			dockedItems: [TaskConsole.views.notesListToolbar]
		});
	
		TaskConsole.views.viewport = new Ext.Panel({
			fullscreen: true,			
			layout: 'card',
			cardAnimation: 'slide',
			items: [TaskConsole.views.notesListContainer]
		});
	
	}	
});


</script>