<a href="<?= $this->baseUrl(); ?>/mobile">
	<div class="item">Home</div>
</a> 	 	 	 
<a href="<?= $this->baseUrl(); ?>/mobile/tasks">
	<div class="item">All Categories</div>
</a> 

<?php foreach( $this->categories as $category ): ?>
	<a href="<?= $this->baseUrl(); ?>/mobile/tasks/category/<?= $category->ID ?>">
		<div class="item"><?= $category->DESCRIPTION ?></div>		
	</a>
	<?php foreach( $category->Projects as $project ): ?>
		<a href="<?= $this->baseUrl(); ?>/mobile/tasks/category/<?= $category->ID ?>/project/<?= $project->ID ?>">
			<div class="sub_item">&#187; <?= $project->DESCRIPTION ?></div>
		</a>
	<?php endforeach; ?>		
<?php endforeach; ?>