<div style="text-align: center; margin-top: 100px;">
	
	<div style="margin-left: auto; margin-right: auto; width: 400px;">
	
		<div style="font-weight: bold; font-size: 18px; padding: 10px 0px;">
			You are now logged out.
		</div>				
		
		<div><a href="<?= $this->baseUrl(); ?>/user/login" style="font-size: 14px; color: blue;">login</a></div>
		
		<div style="padding: 20px 0px; text-align: center;">
			<a href="http://ohapps.com"><img alt="OHAPPS Logo" src="<?= $this->baseUrl(); ?>/html/images/ohapps_logo_small2.png" border=0/></a>
		</div>

	</div>

</div>