<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
	<title>TaskConsole Mobile</title>

	<style type="text/css" media="screen">
	
	    body {
	        margin: 0;
	        font-family: Helvetica;
			font-size: 20px;	        
	        color: #FFFFFF;
	        overflow:hidden;
	    }
	    
	    .container {
	        position: absolute;
	        width: 100%;
	    }
	
	    body[orient="profile"] .container {
	        height: 416px;
	    }
	    
	    body[orient="landscape"] .container {
	        height: 268px;
	    }
	    
	    .toolbar {
	        position: absolute;
	        padding: 10px 0;
	        width: 100%;
	        height: 20px;
	        font-size: 20px;
	        font-weight: bold;
	        text-align: center;
	        text-shadow: #3F4E63 0px -1px 1px;
	        background: url(<?= $this->baseUrl(); ?>/images/iPhoneToolbar.png) #8191AA repeat-x;
	    }
	    
	    body[orient="landscape"] .toolbar {
	        font-size: 20px;
	    }
		
		a {
			text-decoration: none;
		}
	
	    .anchorTop {
	        top: 0;
	    }
	
	    .anchorBottom {
	        border-top: 1px solid #3f4e63;
	        padding-bottom: 9px;
	        bottom: 0;
	    }
	
	    .center {
	        position: absolute;
	        top: 40px;
	        bottom: 40px;
	        background: #FFFFFF;
			width: 100%;
	    }
	
	    body[orient="landscape"] .center {
	        top: 40px;
	        bottom: 40px;
	        width: 100%;
	    }
	    
	    .item {
	        border-bottom: 1px solid #E0E0E0;
	        padding: 8px 32px 8px 8px;
	        color: #000000;
	        background: #B3CCEF;
	        font-weight: bold;
	    }
	    
	    .sub_item {
	        border-bottom: 1px solid #E0E0E0;
	        padding: 8px 32px 8px 20px;
	        color: #000000;	        
	    }
	    
	    .high{
	    	background: #FF9F9F;
	    }
	    
	    .normal{
	    	background: #FEFFAF;
	    }
	    
	    .low{
	    	background: #C2FFAF;
	    }
	    
	</style>

</head>

<body>
    <div class="container">
    	<div class="toolbar anchorTop">TaskConsole Mobile</div>
    	<div class="center">
        	<?= $this->layout()->content ?>
        </div>
    </div>
</body>
</html>
