<!DOCTYPE html>
 <html>
 <head>
     <meta charset="utf-8">
     <title>Task Console Mobile</title>

	 <!-- Sencha Touch CSS -->
	 <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/html/scripts/sencha/resources/css/sencha-touch.css" type="text/css">
	 
	 <!-- Sencha Touch JS -->
	 <script type="text/javascript" src="<?= $this->baseUrl(); ?>/html/scripts/sencha/sencha-touch-debug.js"></script>

 </head>
 <body>
 
 	<?= $this->layout()->content ?>
 
 </body>
 </html>